### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by hosford42** [zikzakmedia/python-mediawiki#3]
Python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
OS: Windows 11

Exception:

```python3
(.venv) PS C:\Users\Aaron Hosford>pip install mediawiki              
Collecting mediawiki
  Downloading mediawiki-0.0.1.tar.gz (22 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Aaron Hosford\PycharmProjects\ExplainableClassifiers\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>  
          main()
        File "C:\Users\Aaron Hosford\PycharmProjects\ExplainableClassifiers\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main      
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Aaron Hosford\PycharmProjects\ExplainableClassifiers\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Aaron Hosford\AppData\Local\Temp\pip-build-env-2jggal1j\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel       
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Aaron Hosford\AppData\Local\Temp\pip-build-env-2jggal1j\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Aaron Hosford\AppData\Local\Temp\pip-build-env-2jggal1j\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Aaron Hosford\AppData\Local\Temp\pip-build-env-2jggal1j\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
        File "C:\Users\Aaron Hosford\AppData\Local\Temp\pip-install-uwrmlzlj\mediawiki_688478c77c904bec86f108622d6afeb4\mediawiki\__init__.py", line 21, in <module>
          from wiki import *
      ModuleNotFoundError: No module named 'wiki'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by hosford42** [comment]
Originally reported [here](https://github.com/barrust/mediawiki/issues/136) due to confusion regarding extremely similar package names.
